// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
// @formatter:off
package main

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"

	"github.com/eidng8/go-admin-areas/ent"
)

func handleErrorResponse(ctx *gin.Context, err error) {
	_ = ctx.Error(err)
	switch {
	case ent.IsValidationError(err):
		ctx.Status(http.StatusUnprocessableEntity)
	case ent.IsNotFound(err):
		ctx.Status(http.StatusNotFound)
	default:
		ctx.Status(http.StatusInternalServerError)
	}
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List AdminAreas
	// (GET /admin-areas)
	ListAdminArea(c *gin.Context, params ListAdminAreaParams)
	// Create a new AdminArea
	// (POST /admin-areas)
	CreateAdminArea(c *gin.Context)
	// Deletes a AdminArea by ID
	// (DELETE /admin-areas/{id})
	DeleteAdminArea(c *gin.Context, id int, params DeleteAdminAreaParams)
	// Find a AdminArea by ID
	// (GET /admin-areas/{id})
	ReadAdminArea(c *gin.Context, id int, params ReadAdminAreaParams)
	// Updates a AdminArea
	// (PATCH /admin-areas/{id})
	UpdateAdminArea(c *gin.Context, id int)
	// List attached Children
	// (GET /admin-areas/{id}/children)
	ListAdminAreaChildren(c *gin.Context, id int, params ListAdminAreaChildrenParams)
	// Find the attached AdminArea
	// (GET /admin-areas/{id}/parent)
	ReadAdminAreaParent(c *gin.Context, id int, params ReadAdminAreaParentParams)
	// Restore a trashed administrative area
	// (POST /admin-areas/{id}/restore)
	RestoreAdminArea(c *gin.Context, id int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListAdminArea operation middleware
func (siw *ServerInterfaceWrapper) ListAdminArea(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAdminAreaParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", c.Request.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter per_page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", c.Request.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "abbr" -------------

	err = runtime.BindQueryParameter("form", true, false, "abbr", c.Request.URL.Query(), &params.Abbr)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter abbr: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "trashed" -------------

	err = runtime.BindQueryParameter("form", true, false, "trashed", c.Request.URL.Query(), &params.Trashed)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter trashed: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAdminArea(c, params)
}

// CreateAdminArea operation middleware
func (siw *ServerInterfaceWrapper) CreateAdminArea(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAdminArea(c)
}

// DeleteAdminArea operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdminArea(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteAdminAreaParams

	// ------------- Optional query parameter "trashed" -------------

	err = runtime.BindQueryParameter("form", true, false, "trashed", c.Request.URL.Query(), &params.Trashed)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter trashed: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAdminArea(c, id, params)
}

// ReadAdminArea operation middleware
func (siw *ServerInterfaceWrapper) ReadAdminArea(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ReadAdminAreaParams

	// ------------- Optional query parameter "trashed" -------------

	err = runtime.BindQueryParameter("form", true, false, "trashed", c.Request.URL.Query(), &params.Trashed)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter trashed: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ReadAdminArea(c, id, params)
}

// UpdateAdminArea operation middleware
func (siw *ServerInterfaceWrapper) UpdateAdminArea(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateAdminArea(c, id)
}

// ListAdminAreaChildren operation middleware
func (siw *ServerInterfaceWrapper) ListAdminAreaChildren(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAdminAreaChildrenParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", c.Request.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter per_page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", c.Request.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "abbr" -------------

	err = runtime.BindQueryParameter("form", true, false, "abbr", c.Request.URL.Query(), &params.Abbr)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter abbr: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "trashed" -------------

	err = runtime.BindQueryParameter("form", true, false, "trashed", c.Request.URL.Query(), &params.Trashed)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter trashed: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "recurse" -------------

	err = runtime.BindQueryParameter("form", true, false, "recurse", c.Request.URL.Query(), &params.Recurse)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter recurse: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAdminAreaChildren(c, id, params)
}

// ReadAdminAreaParent operation middleware
func (siw *ServerInterfaceWrapper) ReadAdminAreaParent(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ReadAdminAreaParentParams

	// ------------- Optional query parameter "trashed" -------------

	err = runtime.BindQueryParameter("form", true, false, "trashed", c.Request.URL.Query(), &params.Trashed)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter trashed: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ReadAdminAreaParent(c, id, params)
}

// RestoreAdminArea operation middleware
func (siw *ServerInterfaceWrapper) RestoreAdminArea(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RestoreAdminArea(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/admin-areas", wrapper.ListAdminArea)
	router.POST(options.BaseURL+"/admin-areas", wrapper.CreateAdminArea)
	router.DELETE(options.BaseURL+"/admin-areas/:id", wrapper.DeleteAdminArea)
	router.GET(options.BaseURL+"/admin-areas/:id", wrapper.ReadAdminArea)
	router.PATCH(options.BaseURL+"/admin-areas/:id", wrapper.UpdateAdminArea)
	router.GET(options.BaseURL+"/admin-areas/:id/children", wrapper.ListAdminAreaChildren)
	router.GET(options.BaseURL+"/admin-areas/:id/parent", wrapper.ReadAdminAreaParent)
	router.POST(options.BaseURL+"/admin-areas/:id/restore", wrapper.RestoreAdminArea)
}

type N400JSONResponse struct {
	Code   int          `json:"code" yaml:"code" xml:"code" bson:"code"`
	Errors *interface{} `json:"errors,omitempty" yaml:"errors,omitempty" xml:"errors,omitempty" bson:"errors,omitempty"`
	Status string       `json:"status" yaml:"status" xml:"status" bson:"status"`
}

type N404JSONResponse struct {
	Code   int          `json:"code" yaml:"code" xml:"code" bson:"code"`
	Errors *interface{} `json:"errors,omitempty" yaml:"errors,omitempty" xml:"errors,omitempty" bson:"errors,omitempty"`
	Status string       `json:"status" yaml:"status" xml:"status" bson:"status"`
}

type N409JSONResponse struct {
	Code   int          `json:"code" yaml:"code" xml:"code" bson:"code"`
	Errors *interface{} `json:"errors,omitempty" yaml:"errors,omitempty" xml:"errors,omitempty" bson:"errors,omitempty"`
	Status string       `json:"status" yaml:"status" xml:"status" bson:"status"`
}

type N500JSONResponse struct {
	Code   int          `json:"code" yaml:"code" xml:"code" bson:"code"`
	Errors *interface{} `json:"errors,omitempty" yaml:"errors,omitempty" xml:"errors,omitempty" bson:"errors,omitempty"`
	Status string       `json:"status" yaml:"status" xml:"status" bson:"status"`
}

type ListAdminAreaRequestObject struct {
	Params ListAdminAreaParams
}

type ListAdminAreaResponseObject interface {
	VisitListAdminAreaResponse(w http.ResponseWriter) error
}

type ListAdminArea200JSONResponse struct {
	// CurrentPage Page number (1-based)
	CurrentPage int `json:"current_page" yaml:"current_page" xml:"current_page" bson:"current_page"`

	// Data List of administrative areas
	Data []AdminAreaList `json:"data" yaml:"data" xml:"data" bson:"data"`

	// FirstPageUrl URL to the first page
	FirstPageUrl string `json:"first_page_url" yaml:"first_page_url" xml:"first_page_url" bson:"first_page_url"`

	// From Index (1-based) of the first item in the current page
	From int `json:"from" yaml:"from" xml:"from" bson:"from"`

	// LastPage Last page number
	LastPage int `json:"last_page" yaml:"last_page" xml:"last_page" bson:"last_page"`

	// LastPageUrl URL to the last page
	LastPageUrl string `json:"last_page_url" yaml:"last_page_url" xml:"last_page_url" bson:"last_page_url"`

	// NextPageUrl URL to the next page
	NextPageUrl string `json:"next_page_url" yaml:"next_page_url" xml:"next_page_url" bson:"next_page_url"`

	// Path Base path of the request
	Path string `json:"path" yaml:"path" xml:"path" bson:"path"`

	// PerPage Number of items per page
	PerPage int `json:"per_page" yaml:"per_page" xml:"per_page" bson:"per_page"`

	// PrevPageUrl URL to the previous page
	PrevPageUrl string `json:"prev_page_url" yaml:"prev_page_url" xml:"prev_page_url" bson:"prev_page_url"`

	// To Index (1-based) of the last item in the current page
	To int `json:"to" yaml:"to" xml:"to" bson:"to"`

	// Total Total number of items
	Total int `json:"total" yaml:"total" xml:"total" bson:"total"`
}

func (response ListAdminArea200JSONResponse) VisitListAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListAdminArea400JSONResponse struct{ N400JSONResponse }

func (response ListAdminArea400JSONResponse) VisitListAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListAdminArea404JSONResponse struct{ N404JSONResponse }

func (response ListAdminArea404JSONResponse) VisitListAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListAdminArea409JSONResponse struct{ N409JSONResponse }

func (response ListAdminArea409JSONResponse) VisitListAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ListAdminArea500JSONResponse struct{ N500JSONResponse }

func (response ListAdminArea500JSONResponse) VisitListAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateAdminAreaRequestObject struct {
	Body *CreateAdminAreaJSONRequestBody
}

type CreateAdminAreaResponseObject interface {
	VisitCreateAdminAreaResponse(w http.ResponseWriter) error
}

type CreateAdminArea200JSONResponse AdminAreaCreate

func (response CreateAdminArea200JSONResponse) VisitCreateAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateAdminArea400JSONResponse struct{ N400JSONResponse }

func (response CreateAdminArea400JSONResponse) VisitCreateAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateAdminArea409JSONResponse struct{ N409JSONResponse }

func (response CreateAdminArea409JSONResponse) VisitCreateAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateAdminArea500JSONResponse struct{ N500JSONResponse }

func (response CreateAdminArea500JSONResponse) VisitCreateAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAdminAreaRequestObject struct {
	Id     int `json:"id" yaml:"id" xml:"id" bson:"id"`
	Params DeleteAdminAreaParams
}

type DeleteAdminAreaResponseObject interface {
	VisitDeleteAdminAreaResponse(w http.ResponseWriter) error
}

type DeleteAdminArea204Response struct {
}

func (response DeleteAdminArea204Response) VisitDeleteAdminAreaResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteAdminArea400JSONResponse struct{ N400JSONResponse }

func (response DeleteAdminArea400JSONResponse) VisitDeleteAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAdminArea404JSONResponse struct{ N404JSONResponse }

func (response DeleteAdminArea404JSONResponse) VisitDeleteAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAdminArea409JSONResponse struct{ N409JSONResponse }

func (response DeleteAdminArea409JSONResponse) VisitDeleteAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAdminArea500JSONResponse struct{ N500JSONResponse }

func (response DeleteAdminArea500JSONResponse) VisitDeleteAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ReadAdminAreaRequestObject struct {
	Id     int `json:"id" yaml:"id" xml:"id" bson:"id"`
	Params ReadAdminAreaParams
}

type ReadAdminAreaResponseObject interface {
	VisitReadAdminAreaResponse(w http.ResponseWriter) error
}

type ReadAdminArea200JSONResponse AdminAreaRead

func (response ReadAdminArea200JSONResponse) VisitReadAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ReadAdminArea400JSONResponse struct{ N400JSONResponse }

func (response ReadAdminArea400JSONResponse) VisitReadAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ReadAdminArea404JSONResponse struct{ N404JSONResponse }

func (response ReadAdminArea404JSONResponse) VisitReadAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ReadAdminArea409JSONResponse struct{ N409JSONResponse }

func (response ReadAdminArea409JSONResponse) VisitReadAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ReadAdminArea500JSONResponse struct{ N500JSONResponse }

func (response ReadAdminArea500JSONResponse) VisitReadAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAdminAreaRequestObject struct {
	Id   int `json:"id" yaml:"id" xml:"id" bson:"id"`
	Body *UpdateAdminAreaJSONRequestBody
}

type UpdateAdminAreaResponseObject interface {
	VisitUpdateAdminAreaResponse(w http.ResponseWriter) error
}

type UpdateAdminArea200JSONResponse AdminAreaUpdate

func (response UpdateAdminArea200JSONResponse) VisitUpdateAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAdminArea400JSONResponse struct{ N400JSONResponse }

func (response UpdateAdminArea400JSONResponse) VisitUpdateAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAdminArea404JSONResponse struct{ N404JSONResponse }

func (response UpdateAdminArea404JSONResponse) VisitUpdateAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAdminArea409JSONResponse struct{ N409JSONResponse }

func (response UpdateAdminArea409JSONResponse) VisitUpdateAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAdminArea500JSONResponse struct{ N500JSONResponse }

func (response UpdateAdminArea500JSONResponse) VisitUpdateAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListAdminAreaChildrenRequestObject struct {
	Id     int `json:"id" yaml:"id" xml:"id" bson:"id"`
	Params ListAdminAreaChildrenParams
}

type ListAdminAreaChildrenResponseObject interface {
	VisitListAdminAreaChildrenResponse(w http.ResponseWriter) error
}

type ListAdminAreaChildren200JSONResponse struct {
	// CurrentPage Page number (1-based)
	CurrentPage int `json:"current_page" yaml:"current_page" xml:"current_page" bson:"current_page"`

	// Data List of administrative areas
	Data []AdminAreaList `json:"data" yaml:"data" xml:"data" bson:"data"`

	// FirstPageUrl URL to the first page
	FirstPageUrl string `json:"first_page_url" yaml:"first_page_url" xml:"first_page_url" bson:"first_page_url"`

	// From Index (1-based) of the first item in the current page
	From int `json:"from" yaml:"from" xml:"from" bson:"from"`

	// LastPage Last page number
	LastPage int `json:"last_page" yaml:"last_page" xml:"last_page" bson:"last_page"`

	// LastPageUrl URL to the last page
	LastPageUrl string `json:"last_page_url" yaml:"last_page_url" xml:"last_page_url" bson:"last_page_url"`

	// NextPageUrl URL to the next page
	NextPageUrl string `json:"next_page_url" yaml:"next_page_url" xml:"next_page_url" bson:"next_page_url"`

	// Path Base path of the request
	Path string `json:"path" yaml:"path" xml:"path" bson:"path"`

	// PerPage Number of items per page
	PerPage int `json:"per_page" yaml:"per_page" xml:"per_page" bson:"per_page"`

	// PrevPageUrl URL to the previous page
	PrevPageUrl string `json:"prev_page_url" yaml:"prev_page_url" xml:"prev_page_url" bson:"prev_page_url"`

	// To Index (1-based) of the last item in the current page
	To int `json:"to" yaml:"to" xml:"to" bson:"to"`

	// Total Total number of items
	Total int `json:"total" yaml:"total" xml:"total" bson:"total"`
}

func (response ListAdminAreaChildren200JSONResponse) VisitListAdminAreaChildrenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListAdminAreaChildren400JSONResponse struct{ N400JSONResponse }

func (response ListAdminAreaChildren400JSONResponse) VisitListAdminAreaChildrenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListAdminAreaChildren404JSONResponse struct{ N404JSONResponse }

func (response ListAdminAreaChildren404JSONResponse) VisitListAdminAreaChildrenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListAdminAreaChildren409JSONResponse struct{ N409JSONResponse }

func (response ListAdminAreaChildren409JSONResponse) VisitListAdminAreaChildrenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ListAdminAreaChildren500JSONResponse struct{ N500JSONResponse }

func (response ListAdminAreaChildren500JSONResponse) VisitListAdminAreaChildrenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ReadAdminAreaParentRequestObject struct {
	Id     int `json:"id" yaml:"id" xml:"id" bson:"id"`
	Params ReadAdminAreaParentParams
}

type ReadAdminAreaParentResponseObject interface {
	VisitReadAdminAreaParentResponse(w http.ResponseWriter) error
}

type ReadAdminAreaParent200JSONResponse AdminAreaParentRead

func (response ReadAdminAreaParent200JSONResponse) VisitReadAdminAreaParentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ReadAdminAreaParent400JSONResponse struct{ N400JSONResponse }

func (response ReadAdminAreaParent400JSONResponse) VisitReadAdminAreaParentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ReadAdminAreaParent404JSONResponse struct{ N404JSONResponse }

func (response ReadAdminAreaParent404JSONResponse) VisitReadAdminAreaParentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ReadAdminAreaParent409JSONResponse struct{ N409JSONResponse }

func (response ReadAdminAreaParent409JSONResponse) VisitReadAdminAreaParentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ReadAdminAreaParent500JSONResponse struct{ N500JSONResponse }

func (response ReadAdminAreaParent500JSONResponse) VisitReadAdminAreaParentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RestoreAdminAreaRequestObject struct {
	Id int `json:"id"`
}

type RestoreAdminAreaResponseObject interface {
	VisitRestoreAdminAreaResponse(w http.ResponseWriter) error
}

type RestoreAdminArea204Response struct {
}

func (response RestoreAdminArea204Response) VisitRestoreAdminAreaResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RestoreAdminArea400JSONResponse struct{ N400JSONResponse }

func (response RestoreAdminArea400JSONResponse) VisitRestoreAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RestoreAdminArea404JSONResponse struct{ N404JSONResponse }

func (response RestoreAdminArea404JSONResponse) VisitRestoreAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RestoreAdminArea409JSONResponse struct{ N409JSONResponse }

func (response RestoreAdminArea409JSONResponse) VisitRestoreAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type RestoreAdminArea500JSONResponse struct{ N500JSONResponse }

func (response RestoreAdminArea500JSONResponse) VisitRestoreAdminAreaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List AdminAreas
	// (GET /admin-areas)
	ListAdminArea(ctx context.Context, request ListAdminAreaRequestObject) (ListAdminAreaResponseObject, error)
	// Create a new AdminArea
	// (POST /admin-areas)
	CreateAdminArea(ctx context.Context, request CreateAdminAreaRequestObject) (CreateAdminAreaResponseObject, error)
	// Deletes a AdminArea by ID
	// (DELETE /admin-areas/{id})
	DeleteAdminArea(ctx context.Context, request DeleteAdminAreaRequestObject) (DeleteAdminAreaResponseObject, error)
	// Find a AdminArea by ID
	// (GET /admin-areas/{id})
	ReadAdminArea(ctx context.Context, request ReadAdminAreaRequestObject) (ReadAdminAreaResponseObject, error)
	// Updates a AdminArea
	// (PATCH /admin-areas/{id})
	UpdateAdminArea(ctx context.Context, request UpdateAdminAreaRequestObject) (UpdateAdminAreaResponseObject, error)
	// List attached Children
	// (GET /admin-areas/{id}/children)
	ListAdminAreaChildren(ctx context.Context, request ListAdminAreaChildrenRequestObject) (ListAdminAreaChildrenResponseObject, error)
	// Find the attached AdminArea
	// (GET /admin-areas/{id}/parent)
	ReadAdminAreaParent(ctx context.Context, request ReadAdminAreaParentRequestObject) (ReadAdminAreaParentResponseObject, error)
	// Restore a trashed administrative area
	// (POST /admin-areas/{id}/restore)
	RestoreAdminArea(ctx context.Context, request RestoreAdminAreaRequestObject) (RestoreAdminAreaResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListAdminArea operation middleware
func (sh *strictHandler) ListAdminArea(ctx *gin.Context, params ListAdminAreaParams) {
	var request ListAdminAreaRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListAdminArea(ctx, request.(ListAdminAreaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAdminArea")
	}

	response, err := handler(ctx, request)

	if err != nil {
		handleErrorResponse(ctx, err)
	} else if validResponse, ok := response.(ListAdminAreaResponseObject); ok {
		if err := validResponse.VisitListAdminAreaResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAdminArea operation middleware
func (sh *strictHandler) CreateAdminArea(ctx *gin.Context) {
	var request CreateAdminAreaRequestObject

	var body CreateAdminAreaJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAdminArea(ctx, request.(CreateAdminAreaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAdminArea")
	}

	response, err := handler(ctx, request)

	if err != nil {
		handleErrorResponse(ctx, err)
	} else if validResponse, ok := response.(CreateAdminAreaResponseObject); ok {
		if err := validResponse.VisitCreateAdminAreaResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAdminArea operation middleware
func (sh *strictHandler) DeleteAdminArea(ctx *gin.Context, id int, params DeleteAdminAreaParams) {
	var request DeleteAdminAreaRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAdminArea(ctx, request.(DeleteAdminAreaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAdminArea")
	}

	response, err := handler(ctx, request)

	if err != nil {
		handleErrorResponse(ctx, err)
	} else if validResponse, ok := response.(DeleteAdminAreaResponseObject); ok {
		if err := validResponse.VisitDeleteAdminAreaResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReadAdminArea operation middleware
func (sh *strictHandler) ReadAdminArea(ctx *gin.Context, id int, params ReadAdminAreaParams) {
	var request ReadAdminAreaRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ReadAdminArea(ctx, request.(ReadAdminAreaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReadAdminArea")
	}

	response, err := handler(ctx, request)

	if err != nil {
		handleErrorResponse(ctx, err)
	} else if validResponse, ok := response.(ReadAdminAreaResponseObject); ok {
		if err := validResponse.VisitReadAdminAreaResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAdminArea operation middleware
func (sh *strictHandler) UpdateAdminArea(ctx *gin.Context, id int) {
	var request UpdateAdminAreaRequestObject

	request.Id = id

	var body UpdateAdminAreaJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAdminArea(ctx, request.(UpdateAdminAreaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAdminArea")
	}

	response, err := handler(ctx, request)

	if err != nil {
		handleErrorResponse(ctx, err)
	} else if validResponse, ok := response.(UpdateAdminAreaResponseObject); ok {
		if err := validResponse.VisitUpdateAdminAreaResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAdminAreaChildren operation middleware
func (sh *strictHandler) ListAdminAreaChildren(ctx *gin.Context, id int, params ListAdminAreaChildrenParams) {
	var request ListAdminAreaChildrenRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListAdminAreaChildren(ctx, request.(ListAdminAreaChildrenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAdminAreaChildren")
	}

	response, err := handler(ctx, request)

	if err != nil {
		handleErrorResponse(ctx, err)
	} else if validResponse, ok := response.(ListAdminAreaChildrenResponseObject); ok {
		if err := validResponse.VisitListAdminAreaChildrenResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReadAdminAreaParent operation middleware
func (sh *strictHandler) ReadAdminAreaParent(ctx *gin.Context, id int, params ReadAdminAreaParentParams) {
	var request ReadAdminAreaParentRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ReadAdminAreaParent(ctx, request.(ReadAdminAreaParentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReadAdminAreaParent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		handleErrorResponse(ctx, err)
	} else if validResponse, ok := response.(ReadAdminAreaParentResponseObject); ok {
		if err := validResponse.VisitReadAdminAreaParentResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RestoreAdminArea operation middleware
func (sh *strictHandler) RestoreAdminArea(ctx *gin.Context, id int) {
	var request RestoreAdminAreaRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RestoreAdminArea(ctx, request.(RestoreAdminAreaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RestoreAdminArea")
	}

	response, err := handler(ctx, request)

	if err != nil {
		handleErrorResponse(ctx, err)
	} else if validResponse, ok := response.(RestoreAdminAreaResponseObject); ok {
		if err := validResponse.VisitRestoreAdminAreaResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaUW/bNhD+KwS3hw1QY7dNH+q3tNmAAEERpO32UBTBWTzb7CRSJSknQaH/PhwpWbIl",
	"y3bTrvGqhyC2fDreHb873n3SFx7rNNMKlbN88oUbtJlWFv2X0/GY/sVaOVSOPkKWJTIGJ7UafbJa0TUb",
	"LzAF+pQZnaFxMtwda4H0391nyCdcKodzNLyIOBqjDckUEbcOXG4bctYZqea8KCJu8HMuDQo++RC0rcQ/",
	"RpW4nn7C2PGC5AXa2MiMrPMLLiGRgkmV5S5iAhyw8hoZcTo+PWLnDFqdmxiZ0o7NdK5Kn14esU+xVrNE",
	"xk6qOav8s7T8i6PGYa7wLsPYoWB+Qa8yGOvXOxOpVGcGO0yH6dTQ/3WF/gZpnQEnl8jAIDCSxKX0EbER",
	"e/32L7aEJEfLI57C3SWquVvwybMXLyKeSlV9fxpxlScJTBPkE2dyjDbdj3i8kIkw6GMsHabesl8NzviE",
	"/zKqy8eo9GlUO1Ss1IExcO+1GQSH4gb8Ps60SekTF+DwiZMpxbZlgRQkS06neeqNbu9liqluh+oaUzD/",
	"fIMgKEhxv53wkr3rPevQn4Epob13ZMMtN/sEJ8/EgUHfQL0UvIxBG/FRjeDXfnMfK44H5G1H3qOC0aW0",
	"bgDRAKIHgegaQQwgGkD0IBC99+sMMBpg9CAY3Vx5m4aSNGDp67BEslLNOkL5biEtk5aBYpA7zeao0JAh",
	"7OzqgjVkWQoCmc4d0zOS/kM5FuYKJnAmlfQKI+6ko4Bz+v1t+P3s6oJHfInGhjXHJ09PxuSzzlBBJvmE",
	"Pz8ZnzznFDC38KgeAW3CE4q9/z5H1zaeGj22yhJ7wr1K4wF+IUqBeujx+wEpOqSp/cOmttsFOJbBHJnT",
	"zKASaDiFjU/45xzNfRXeCSchHjUYg76tLaLNhWgKZrHOlatXYhn9Bb2dS6K5aS8Ld2HZCosHGPEGUqSt",
	"dAtk0Ab8FjPKNFgzYf+EaFtx1ihJPdZELAbFpsjAV62EGvxuA301/IYG/r1At0BDGyVVnOQCmTNgFyhY",
	"IDO6zShl1iwp15pqnSAoXhQfo3W+9NnDeKrc+GLjUdJKlSvCtcrTKRr229MnU7AofufRjqIkwMGWtKMq",
	"0N4oH4+DSB4/rHUQPTNpbHDmJjdJ24j315e0KQQYL1olT6sGz4xO27dfKIF3dSQq7AVVPkGl8lfKsFbq",
	"V/Ead8UrAbttAy6htLHchZ2xX+na6X8CPe4rvNtTDUluVUOFuX33K7DI6KcqfnQgoU/OtoaqgrW0vAmw",
	"1LOQUs1S2B+izOByP99IUurcbvXP6b0x4sP91RBx2kGHre/ocpWgVSR2KNuklpsFoFooap4cNTzLtPB+",
	"t3JtE3ubINoMfImOslzsw2lfwVwq32UkfbXEP5IYbyslq9o5IqH6kcwu2dPGo45dsi8bzw/6ZUnIM/N5",
	"moK5b3cnFGyYU+PRoOw/Eoq17ehtAhdqGTCFt7UaBkpQglhpnWXSdxDWaQNzbLc/QUezASrz85UW9wcd",
	"NSCEb/AguWocOjNILEaPcR75WeaGjRLQ0/53mOrx5DQLwxtvqiK/iwe2J3sd/yXl32tiOVweXg6+e4oH",
	"6zdzdEumF9HaVDP6IkURQJSg64DTub9u/RFTB+NWukXzqEXBLs7bqR9u3nv2uTivTrfmLb6zLWt72dj6",
	"KXMdJ3sPQu1+93RLEtWeNr1kt2BZiJY48rOh2lto7Oz0nl2cbz0lOgfgP6USewHEHxsGXW4UnRptvFwj",
	"iMeFlqMaxfaqdZ6/66103ZBvvJ9xtIAnpB6A9gxc3DFvBD59PW3WGqJ4AWpONbOnKwpKHmFpHFqz/1lr",
	"dkAbVm8UYTeQwT+mIyufWfVaW5LVR16TOqrJAa3bqPli03Z6GpyDmM6o16X4Lpq6knuch/ADSPL/kBgf",
	"6O+B/h7o74H+Hujvgf4e6O8fSH+3u59DOqz6reat7Ec4MqtV6g51szWqaZG5XKIKs2cPBRLeuBmIkO8y",
	"YjTfZ+qdM1Yb6zT7aViSbkRvy5ui+DcAAP//vTNvyYQ1AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
