// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package main

import (
	"time"

	"github.com/oapi-codegen/nullable"
)

// AdminArea defines model for AdminArea.
type AdminArea struct {
	// Abbr Administrative area abbreviations, CSV values
	Abbr      nullable.Nullable[string] `json:"abbr,omitempty"`
	Children  *[]AdminArea              `json:"children,omitempty"`
	CreatedAt *time.Time                `json:"created_at,omitempty"`
	Id        int                       `json:"id"`

	// Memo Remarks
	Memo nullable.Nullable[string] `json:"memo,omitempty"`

	// Name Administrative area name
	Name      string     `json:"name"`
	Parent    *AdminArea `json:"parent,omitempty"`
	ParentId  *int       `json:"parent_id,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// AdminAreaCreate defines model for AdminAreaCreate.
type AdminAreaCreate struct {
	// Abbr Administrative area abbreviations, CSV values
	Abbr      nullable.Nullable[string] `json:"abbr,omitempty"`
	CreatedAt *time.Time                `json:"created_at,omitempty"`
	Id        int                       `json:"id"`

	// Memo Remarks
	Memo nullable.Nullable[string] `json:"memo,omitempty"`

	// Name Administrative area name
	Name      string     `json:"name"`
	ParentId  *int       `json:"parent_id,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// AdminAreaList defines model for AdminAreaList.
type AdminAreaList struct {
	// Abbr Administrative area abbreviations, CSV values
	Abbr      nullable.Nullable[string] `json:"abbr,omitempty"`
	CreatedAt *time.Time                `json:"created_at,omitempty"`
	Id        int                       `json:"id"`

	// Memo Remarks
	Memo nullable.Nullable[string] `json:"memo,omitempty"`

	// Name Administrative area name
	Name      string     `json:"name"`
	ParentId  *int       `json:"parent_id,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// AdminAreaRead defines model for AdminAreaRead.
type AdminAreaRead struct {
	// Abbr Administrative area abbreviations, CSV values
	Abbr      nullable.Nullable[string] `json:"abbr,omitempty"`
	CreatedAt *time.Time                `json:"created_at,omitempty"`
	Id        int                       `json:"id"`

	// Memo Remarks
	Memo nullable.Nullable[string] `json:"memo,omitempty"`

	// Name Administrative area name
	Name      string     `json:"name"`
	ParentId  *int       `json:"parent_id,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// AdminAreaUpdate defines model for AdminAreaUpdate.
type AdminAreaUpdate struct {
	// Abbr Administrative area abbreviations, CSV values
	Abbr      nullable.Nullable[string] `json:"abbr,omitempty"`
	CreatedAt *time.Time                `json:"created_at,omitempty"`
	Id        int                       `json:"id"`

	// Memo Remarks
	Memo nullable.Nullable[string] `json:"memo,omitempty"`

	// Name Administrative area name
	Name      string     `json:"name"`
	ParentId  *int       `json:"parent_id,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// AdminAreaChildrenList defines model for AdminArea_ChildrenList.
type AdminAreaChildrenList struct {
	// Abbr Administrative area abbreviations, CSV values
	Abbr      nullable.Nullable[string] `json:"abbr,omitempty"`
	CreatedAt *time.Time                `json:"created_at,omitempty"`
	Id        int                       `json:"id"`

	// Memo Remarks
	Memo nullable.Nullable[string] `json:"memo,omitempty"`

	// Name Administrative area name
	Name      string     `json:"name"`
	ParentId  *int       `json:"parent_id,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// AdminAreaParentRead defines model for AdminArea_ParentRead.
type AdminAreaParentRead struct {
	// Abbr Administrative area abbreviations, CSV values
	Abbr      nullable.Nullable[string] `json:"abbr,omitempty"`
	CreatedAt *time.Time                `json:"created_at,omitempty"`
	Id        int                       `json:"id"`

	// Memo Remarks
	Memo nullable.Nullable[string] `json:"memo,omitempty"`

	// Name Administrative area name
	Name      string     `json:"name"`
	ParentId  *int       `json:"parent_id,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// N400 defines model for 400.
type N400 struct {
	Code   int          `json:"code"`
	Errors *interface{} `json:"errors,omitempty"`
	Status string       `json:"status"`
}

// N404 defines model for 404.
type N404 struct {
	Code   int          `json:"code"`
	Errors *interface{} `json:"errors,omitempty"`
	Status string       `json:"status"`
}

// N409 defines model for 409.
type N409 struct {
	Code   int          `json:"code"`
	Errors *interface{} `json:"errors,omitempty"`
	Status string       `json:"status"`
}

// N500 defines model for 500.
type N500 struct {
	Code   int          `json:"code"`
	Errors *interface{} `json:"errors,omitempty"`
	Status string       `json:"status"`
}

// ListAdminAreaParams defines parameters for ListAdminArea.
type ListAdminAreaParams struct {
	// Page what page to render
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PerPage item count to render per page
	PerPage *int `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// CreateAdminAreaJSONBody defines parameters for CreateAdminArea.
type CreateAdminAreaJSONBody struct {
	// Abbr Administrative area abbreviations, CSV values
	Abbr nullable.Nullable[string] `json:"abbr,omitempty"`

	// Memo Remarks
	Memo nullable.Nullable[string] `json:"memo,omitempty"`

	// Name Administrative area name
	Name     string `json:"name"`
	ParentId *int   `json:"parent_id,omitempty"`
}

// UpdateAdminAreaJSONBody defines parameters for UpdateAdminArea.
type UpdateAdminAreaJSONBody struct {
	// Abbr Administrative area abbreviations, CSV values
	Abbr nullable.Nullable[string] `json:"abbr,omitempty"`

	// Memo Remarks
	Memo nullable.Nullable[string] `json:"memo,omitempty"`

	// Name Administrative area name
	Name     *string `json:"name,omitempty"`
	ParentId *int    `json:"parent_id,omitempty"`
}

// ListAdminAreaChildrenParams defines parameters for ListAdminAreaChildren.
type ListAdminAreaChildrenParams struct {
	// Page what page to render
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PerPage item count to render per page
	PerPage *int `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// CreateAdminAreaJSONRequestBody defines body for CreateAdminArea for application/json ContentType.
type CreateAdminAreaJSONRequestBody CreateAdminAreaJSONBody

// UpdateAdminAreaJSONRequestBody defines body for UpdateAdminArea for application/json ContentType.
type UpdateAdminAreaJSONRequestBody UpdateAdminAreaJSONBody
